name: Use Secret

on:
  push:
    branches: [ "main" ]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show message
        run: echo "Using secret safely"

      - name: Use Secret
        run: echo "Secret accessed"
        env:
          API_KEY: ${{ secrets.API_KEY }}
